Add description of dynamic detail geometry functionality
teksi/wastewater pull request #413
Opened 2024-09-11 11:03 UTC by cymed

2024-09-11 11:21 UTC, urskaufmann requested changes
is created is created: just once in line 26

2024-09-12 10:46 UTC, urskaufmann approved these changes
right, it's a view...

2024-09-18 07:57 UTC, ponceta commented
![image](https://github.com/user-attachments/assets/9cd50ecd-32b6-4534-a3a7-ab14764c22a9)

2024-09-18 07:58 UTC, ponceta approved these changes

2024-09-18 07:58 UTC, merged